language: objective-c
osx_image: xcode8.3

script:
    - xcodebuild clean && xcodebuild clean build -sdk iphonesimulator -project MulticastDelegate.xcodeproj -scheme MulticastDelegate CODE_SIGNING_REQUIRED=NO
