language: objective-c
osx_image: xcode10

script:
  - xcodebuild clean build-for-testing -sdk iphonesimulator -project MulticastDelegate.xcodeproj -scheme iOS\ Tests CODE_SIGNING_REQUIRED=NO
  - xctool -project MulticastDelegate.xcodeproj -scheme iOS\ Tests -sdk iphonesimulator run-tests 

  - xcodebuild clean build-for-testing -sdk appletvsimulator -project MulticastDelegate.xcodeproj -scheme tvOS\ Tests CODE_SIGNING_REQUIRED=NO
  - xctool -project MulticastDelegate.xcodeproj -scheme tvOS\ Tests -sdk appletvsimulator run-tests 